env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'airbnb'
  - 'airbnb/hooks'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  indent:
    - error
    - tab
    - SwitchCase: 1
  linebreak-style:
    - off
    - unix
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - always
  no-tabs: off
  '@typescript-eslint/no-empty-interface': off
  '@typescript-eslint/member-delimiter-style':
    - error
    - multiline:
        delimiter: none
      singleline:
        delimiter: comma
  '@typescript-eslint/explicit-function-return-type': off
  no-use-before-define: off
  '@typescript-eslint/no-use-before-define': off
  react/state-in-constructor: off
  import/no-default-export: error
  import/prefer-default-export: off
  object-curly-spacing:
    - error
    - never
  max-len: off
  no-nested-ternary: off
  no-underscore-dangle: off
  react/jsx-indent:
    - error
    - tab
    - checkAttributes: true
      indentLogicalExpressions: true
  react/jsx-indent-props:
    - error
    - tab
  react/jsx-filename-extension:
    - error
    - extensions:
      - .jsx
      - .tsx
  no-return-assign: off
  react/sort-comp: off
  react/destructuring-assignment: off
  no-mixed-operators: off
  arrow-parens: off
  no-else-return: off
  no-shadow: off
  object-curly-newline:
    - error
    - multiline: true
      consistent: true
  operator-linebreak: off
  react/no-array-index-key: off
  react/jsx-curly-brace-presence: off
  no-unused-expressions: off
  react/prefer-stateless-function: off
  arrow-body-style: off
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
      - '**/*.test.js'
      - '**/*.test.ts'
      - '**/*.test.tsx'
      - 'app/test-utils/**/*'
  prefer-arrow-callback: off
  react/jsx-props-no-spreading: off
  react/jsx-one-expression-per-line: off
  func-names: off
  no-plusplus: off
  no-continue: off
  react/prop-types: off
  jsx-a11y/alt-text: off
  jsx-a11y/no-static-element-interactions: off
  jsx-a11y/click-events-have-key-events: off
  jsx-a11y/anchor-has-content: off
  jsx-a11y/aria-role: off
  jsx-a11y/aria-props: off
  jsx-a11y/aria-proptypes: off
  jsx-a11y/aria-unsupported-elements: off
  jsx-a11y/img-redundant-alt: off
  jsx-a11y/label-has-for: off
  jsx-a11y/label-has-associated-control: off
  jsx-a11y/control-has-associated-label: off
  jsx-a11y/mouse-events-have-key-events: off
  jsx-a11y/no-access-key: off
  jsx-a11y/no-onchange: off
  jsx-a11y/interactive-supports-focus: off
  jsx-a11y/role-has-required-aria-props: off
  jsx-a11y/role-supports-aria-props: off
  jsx-a11y/tabindex-no-positive: off
  jsx-a11y/heading-has-content: off
  jsx-a11y/html-has-lang: off
  jsx-a11y/lang: off
  jsx-a11y/no-distracting-elements: off
  jsx-a11y/scope: off
  jsx-a11y/no-noninteractive-element-interactions: off
  jsx-a11y/accessible-emoji: off
  jsx-a11y/aria-activedescendant-has-tabindex: off
  jsx-a11y/iframe-has-title: off
  jsx-a11y/no-autofocus: off
  jsx-a11y/no-redundant-roles: off
  jsx-a11y/media-has-caption: off
  jsx-a11y/no-interactive-element-to-noninteractive-role: off
  jsx-a11y/no-noninteractive-element-to-interactive-role: off
  jsx-a11y/no-noninteractive-tabindex: off
  jsx-a11y/anchor-is-valid: off
  no-useless-constructor: off
  no-param-reassign: off
  max-classes-per-file: off
  no-restricted-syntax: off
  '@typescript-eslint/interface-name-prefix': off
  operator-assignment: off
  '@typescript-eslint/no-unused-vars':
    - error
    - ignoreRestSiblings: true
  consistent-return: off
  no-empty:
    - error
    - allowEmptyCatch: true
  react/button-has-type: off
  react/jsx-tag-spacing: off
  global-require: off
  implicit-arrow-linebreak: off
  react/jsx-boolean-value: off
  react/jsx-no-target-blank: off
  prefer-destructuring: off
  import/extensions: off
  react/no-children-prop: off
  no-multi-assign: off
  react/no-danger: off
  prefer-template: off
  react/no-unescaped-entities: off
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/ban-types': off
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
